/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Darwin ehes-mbp.wifi.local.cmu.edu 20.3.0 x86_64"
#define YALS_COMPILED "Tue Mar 22 21:31:23 EDT 2022"
#define YALS_RELEASED "Fr 1. Mär 05:17:48 CET 2019"
#define YALS_VERSION "03v"
#define YALS_ID "b1316746d40f72f147cde3f4ec54fadbe0730427"
